import type {
  AutomationRule,
  AvailableSlot,
  BillingEntry,
  ClinicalRecord,
  ClinicalAttachment,
  Consent,
  MessageTemplate,
  Note,
  Notification,
  Patient,
  PatientTimelineItem,
  TherapySession,
} from "@/lib/domain";

export const psychologistProfile = {
  name: "Dra. Marina Azevedo",
  crp: "CRP 06/123456",
  email: "marina@clinicaia.local",
  whatsapp: "+55 11 98888-0101",
  city: "São Paulo, SP",
};

export const agentSettings = {
  persona: "Acolhedor, objetivo e com linguagem simples",
  approach: "TCC",
  pricingStrategy: "Informa faixa de R$ 180 a R$ 240 quando perguntado",
  officeHours: ["Seg, qua e sex: 08:00-18:00", "Ter e qui: 10:00-20:00"],
  waitlistAcceptanceHours: 3,
  childCareEnabled: false,
};

export const patients: Patient[] = [
  {
    id: "pat_ana",
    name: "Ana Ribeiro",
    whatsapp: "+55 11 97777-1212",
    email: "ana.ribeiro@email.com",
    birthDate: "1991-04-18",
    modality: "online",
    archived: false,
    generalNotes: "Prefere atendimento no fim da tarde.",
    financialStatus: "PENDENTE",
    nextSession: "2026-05-16T16:00:00-03:00",
    alerts: ["Documentos pendentes", "Pagamento pendente"],
    lastContactAt: "2026-05-16T09:12:00-03:00",
    documentsPending: 2,
    consentStatus: "pending",
    attachmentCount: 3,
    lastClinicalUpdate: "2026-05-12T18:40:00-03:00",
  },
  {
    id: "pat_carlos",
    name: "Carlos Mendes",
    whatsapp: "+55 11 96666-3434",
    modality: "presencial",
    archived: false,
    financialStatus: "PAGO",
    nextSession: "2026-05-16T10:00:00-03:00",
    waitlistPosition: 1,
    alerts: ["Preferência por presencial"],
    lastContactAt: "2026-05-15T18:40:00-03:00",
    documentsPending: 0,
    consentStatus: "complete",
    attachmentCount: 4,
    lastClinicalUpdate: "2026-05-08T12:20:00-03:00",
  },
  {
    id: "pat_luiza",
    name: "Luiza Martins",
    whatsapp: "+55 11 95555-9090",
    email: "luiza@email.com",
    birthDate: "1987-11-02",
    modality: "online",
    archived: false,
    financialStatus: "PENDENTE",
    nextSession: "2026-05-18T14:00:00-03:00",
    alerts: ["Lead convertido pelo SDR"],
    lastContactAt: "2026-05-13T17:14:00-03:00",
    documentsPending: 1,
    consentStatus: "pending",
    attachmentCount: 1,
    lastClinicalUpdate: "2026-05-13T17:14:00-03:00",
  },
  {
    id: "pat_renato",
    name: "Renato Freitas",
    whatsapp: "+55 11 94444-7878",
    modality: "presencial",
    archived: false,
    financialStatus: "PAGO",
    alerts: ["Prontuário concluído"],
    lastContactAt: "2026-05-13T10:30:00-03:00",
    documentsPending: 0,
    consentStatus: "complete",
    attachmentCount: 2,
    lastClinicalUpdate: "2026-05-13T10:10:00-03:00",
  },
];

export const sessions: TherapySession[] = [
  {
    id: "ses_1001",
    patientId: "pat_ana",
    patientName: "Ana Ribeiro",
    startsAt: "2026-05-16T16:00:00-03:00",
    endsAt: "2026-05-16T16:50:00-03:00",
    modality: "online",
    status: "AGENDADA",
    paymentStatus: "PENDENTE",
    origin: "dashboard",
    location: "Link de videochamada",
    serviceType: "Psicoterapia individual",
    reminderStatus: "sent",
    documentationStatus: "not_started",
    confirmationStatus: "confirmed",
    attendanceStatus: "expected",
    amountCents: 22000,
    invoiceStatus: "queued",
    chargeStatus: "pix_sent",
    receiptStatus: "ready",
  },
  {
    id: "ses_1002",
    patientId: "pat_carlos",
    patientName: "Carlos Mendes",
    startsAt: "2026-05-16T10:00:00-03:00",
    endsAt: "2026-05-16T10:50:00-03:00",
    modality: "presencial",
    status: "REMANEJADA",
    paymentStatus: "PAGO",
    origin: "whatsapp_recepcionista",
    location: "Sala 2",
    serviceType: "Retorno",
    reminderStatus: "scheduled",
    documentationStatus: "draft",
    confirmationStatus: "rescheduled",
    attendanceStatus: "expected",
    amountCents: 20000,
    invoiceStatus: "ready",
    chargeStatus: "paid",
    receiptStatus: "sent",
  },
  {
    id: "ses_1003",
    patientId: "pat_luiza",
    patientName: "Luiza Martins",
    startsAt: "2026-05-18T14:00:00-03:00",
    endsAt: "2026-05-18T14:50:00-03:00",
    modality: "online",
    status: "AGENDADA",
    paymentStatus: "PENDENTE",
    origin: "whatsapp_sdr",
    location: "Link de videochamada",
    serviceType: "Primeira sessão",
    reminderStatus: "scheduled",
    documentationStatus: "not_started",
    confirmationStatus: "pending",
    attendanceStatus: "expected",
    amountCents: 24000,
    invoiceStatus: "ready",
    chargeStatus: "pix_sent",
    receiptStatus: "not_ready",
  },
  {
    id: "ses_1004",
    patientId: "pat_renato",
    patientName: "Renato Freitas",
    startsAt: "2026-05-13T09:00:00-03:00",
    endsAt: "2026-05-13T09:50:00-03:00",
    modality: "presencial",
    status: "CONCLUIDA",
    paymentStatus: "PAGO",
    origin: "dashboard",
    location: "Sala 1",
    serviceType: "Psicoterapia individual",
    reminderStatus: "sent",
    documentationStatus: "complete",
    confirmationStatus: "confirmed",
    attendanceStatus: "present",
    amountCents: 22000,
    invoiceStatus: "issued",
    chargeStatus: "paid",
    receiptStatus: "sent",
  },
  {
    id: "ses_1005",
    patientId: "pat_ana",
    patientName: "Ana Ribeiro",
    startsAt: "2026-05-23T16:00:00-03:00",
    endsAt: "2026-05-23T16:50:00-03:00",
    modality: "online",
    status: "AGENDADA",
    paymentStatus: "PENDENTE",
    origin: "dashboard",
    location: "Link de videochamada",
    serviceType: "Recorrente semanal",
    reminderStatus: "scheduled",
    documentationStatus: "not_started",
    confirmationStatus: "pending",
    attendanceStatus: "expected",
    amountCents: 22000,
    invoiceStatus: "not_required",
    chargeStatus: "not_sent",
    receiptStatus: "not_ready",
  },
];

export const records: ClinicalRecord[] = [
  {
    id: "rec_5001",
    patientId: "pat_renato",
    patientName: "Renato Freitas",
    template: "DAP",
    sessionDate: "2026-05-13T09:00:00-03:00",
    createdAt: "2026-05-13T10:10:00-03:00",
    archived: false,
    retentionUntil: "2031-05-13T10:10:00-03:00",
    fields: [
      {
        label: "Descrição",
        value: "Relato breve registrado manualmente pelo profissional.",
      },
      {
        label: "Avaliação",
        value: "Formulação clínica mantida no dashboard, sem uso de IA.",
      },
      {
        label: "Plano",
        value: "Combinar continuidade e revisar objetivos na próxima sessão.",
      },
    ],
    contextSummary:
      "Evolucao vinculada a sessao concluida, com plano de continuidade e sigilo preservado.",
    attachments: ["Contrato terapeutico", "Termo LGPD"],
    consentIds: ["cons_renato_lgpd"],
  },
  {
    id: "rec_5002",
    patientId: "pat_carlos",
    patientName: "Carlos Mendes",
    template: "BIRP",
    sessionDate: "2026-05-08T11:00:00-03:00",
    createdAt: "2026-05-08T12:20:00-03:00",
    archived: false,
    retentionUntil: "2031-05-08T12:20:00-03:00",
    fields: [
      {
        label: "Comportamento",
        value: "Observações inseridas diretamente pela psicóloga.",
      },
      {
        label: "Intervenção",
        value: "Técnicas e intervenções descritas manualmente.",
      },
      {
        label: "Resposta",
        value: "Resposta do paciente documentada no prontuário.",
      },
      {
        label: "Plano",
        value: "Próximos passos e acompanhamento.",
      },
    ],
    contextSummary:
      "Registro em rascunho com historico de retornos, preferencia presencial e documentos assinados.",
    attachments: ["Anamnese inicial", "Plano de tratamento"],
    consentIds: ["cons_carlos_lgpd"],
  },
];

export const notes: Note[] = [
  {
    id: "note_1",
    patientId: "pat_ana",
    patientName: "Ana Ribeiro",
    createdAt: "2026-05-12T18:40:00-03:00",
    body: "Anotação atemporal da ficha; pode ser removida a qualquer momento.",
  },
  {
    id: "note_2",
    patientId: "pat_renato",
    patientName: "Renato Freitas",
    sessionId: "ses_1004",
    createdAt: "2026-05-13T10:05:00-03:00",
    body: "Nota vinculada à sessão; acompanha a regra de retenção clínica.",
  },
];

export const notifications: Notification[] = [
  {
    id: "not_1",
    title: "Lead qualificado pelo SDR",
    detail: "Luiza aceitou modalidade online e faixa financeira.",
    createdAt: "2026-05-13T17:12:00-03:00",
    type: "lead",
  },
  {
    id: "not_2",
    title: "Sessão agendada automaticamente",
    detail: "Nova sessão online para 18/05 às 14:00.",
    createdAt: "2026-05-13T17:14:00-03:00",
    type: "session",
  },
  {
    id: "not_3",
    title: "Pedido para falar com a psicóloga",
    detail: "Paciente pediu orientação fora do escopo administrativo.",
    createdAt: "2026-05-16T08:30:00-03:00",
    type: "handoff",
  },
  {
    id: "not_4",
    title: "Horário liberado para fila de espera",
    detail: "Carlos está em primeiro lugar para amanhã às 11:00.",
    createdAt: "2026-05-16T11:20:00-03:00",
    type: "reschedule",
  },
];

export const availableSlots: AvailableSlot[] = [
  {
    id: "slot_1",
    startsAt: "2026-05-16T17:00:00-03:00",
    endsAt: "2026-05-16T17:50:00-03:00",
    modality: "online",
  },
  {
    id: "slot_2",
    startsAt: "2026-05-17T11:00:00-03:00",
    endsAt: "2026-05-17T11:50:00-03:00",
    modality: "presencial",
  },
  {
    id: "slot_3",
    startsAt: "2026-05-18T09:00:00-03:00",
    endsAt: "2026-05-18T09:50:00-03:00",
    modality: "online",
  },
];

export const billingEntries: BillingEntry[] = [
  {
    id: "bill_1001",
    sessionId: "ses_1001",
    patientId: "pat_ana",
    patientName: "Ana Ribeiro",
    serviceDate: "2026-05-16T16:00:00-03:00",
    serviceType: "Psicoterapia individual",
    amountCents: 22000,
    paymentStatus: "PENDENTE",
    chargeStatus: "pix_sent",
    invoiceStatus: "queued",
    receiptStatus: "ready",
    dueDate: "2026-05-16T23:59:00-03:00",
  },
  {
    id: "bill_1002",
    sessionId: "ses_1002",
    patientId: "pat_carlos",
    patientName: "Carlos Mendes",
    serviceDate: "2026-05-16T10:00:00-03:00",
    serviceType: "Retorno",
    amountCents: 20000,
    paymentStatus: "PAGO",
    chargeStatus: "paid",
    invoiceStatus: "ready",
    receiptStatus: "sent",
    dueDate: "2026-05-16T23:59:00-03:00",
    paidAt: "2026-05-15T19:10:00-03:00",
  },
  {
    id: "bill_1003",
    sessionId: "ses_1003",
    patientId: "pat_luiza",
    patientName: "Luiza Martins",
    serviceDate: "2026-05-18T14:00:00-03:00",
    serviceType: "Primeira sessão",
    amountCents: 24000,
    paymentStatus: "PENDENTE",
    chargeStatus: "pix_sent",
    invoiceStatus: "ready",
    receiptStatus: "not_ready",
    dueDate: "2026-05-18T23:59:00-03:00",
  },
  {
    id: "bill_1004",
    sessionId: "ses_1004",
    patientId: "pat_renato",
    patientName: "Renato Freitas",
    serviceDate: "2026-05-13T09:00:00-03:00",
    serviceType: "Psicoterapia individual",
    amountCents: 22000,
    paymentStatus: "PAGO",
    chargeStatus: "paid",
    invoiceStatus: "issued",
    receiptStatus: "sent",
    dueDate: "2026-05-13T23:59:00-03:00",
    paidAt: "2026-05-13T09:58:00-03:00",
  },
];

export const messageTemplates: MessageTemplate[] = [
  {
    id: "tpl_confirmacao_24h",
    title: "Confirmação 24h",
    category: "confirmacao",
    channel: "whatsapp",
    approved: true,
    tone: "Acolhedor e objetivo",
    body: "Olá, {{nome}}. Passando para confirmar sua sessão de {{data}} às {{hora}}. Posso manter esse horário?",
  },
  {
    id: "tpl_reagendamento",
    title: "Reagendamento automático",
    category: "reagendamento",
    channel: "whatsapp",
    approved: true,
    tone: "Humano, sem pressão",
    body: "Sem problema. Tenho estes horários disponíveis: {{slots}}. Qual deles funciona melhor para você?",
  },
  {
    id: "tpl_documentos",
    title: "Documentos pendentes",
    category: "documentos",
    channel: "whatsapp",
    approved: true,
    tone: "Claro e respeitoso",
    body: "Antes da sessão, falta assinar {{documentos}}. O link seguro é {{link}}.",
  },
  {
    id: "tpl_cobranca",
    title: "Cobrança com Pix",
    category: "cobranca",
    channel: "whatsapp",
    approved: true,
    tone: "Discreto",
    body: "Enviei o Pix referente ao atendimento de {{data}}. Assim que o pagamento cair, o recibo fica disponível.",
  },
];

export const automationRules: AutomationRule[] = [
  {
    id: "auto_confirmacao",
    title: "Confirmar sessão 24h antes",
    trigger: "Sessão agendada com menos de 24h",
    action: "Enviar template aprovado e registrar resposta",
    status: "active",
    humanTone: "Acolhedor, com opção clara de confirmar ou remarcar",
    lastRunAt: "2026-05-16T09:00:00-03:00",
  },
  {
    id: "auto_reagendamento",
    title: "Reagendar sem troca manual",
    trigger: "Paciente responde que não pode comparecer",
    action: "Consultar slots, oferecer horários e atualizar agenda",
    status: "active",
    humanTone: "Sem culpa, mantendo vínculo e previsibilidade",
    lastRunAt: "2026-05-16T11:20:00-03:00",
  },
  {
    id: "auto_nfse",
    title: "Emitir NFS-e após pagamento",
    trigger: "Pagamento confirmado",
    action: "Preparar nota fiscal e recibo do atendimento",
    status: "active",
    humanTone: "Operação silenciosa; paciente recebe só o necessário",
    lastRunAt: "2026-05-15T19:12:00-03:00",
  },
];

export const clinicalAttachments: ClinicalAttachment[] = [
  {
    id: "att_ana_termo",
    patientId: "pat_ana",
    title: "Termo LGPD pendente",
    kind: "termo",
    createdAt: "2026-05-12T18:20:00-03:00",
    protected: true,
  },
  {
    id: "att_carlos_anamnese",
    patientId: "pat_carlos",
    title: "Anamnese inicial",
    kind: "documento",
    createdAt: "2026-05-08T10:30:00-03:00",
    protected: true,
  },
  {
    id: "att_renato_contrato",
    patientId: "pat_renato",
    title: "Contrato terapêutico",
    kind: "documento",
    createdAt: "2026-05-13T08:30:00-03:00",
    protected: true,
  },
];

export const consents: Consent[] = [
  {
    id: "cons_ana_lgpd",
    patientId: "pat_ana",
    title: "Consentimento LGPD",
    status: "pending",
    expiresAt: "2026-05-23T23:59:00-03:00",
  },
  {
    id: "cons_carlos_lgpd",
    patientId: "pat_carlos",
    title: "Consentimento LGPD",
    status: "signed",
    signedAt: "2026-05-08T10:15:00-03:00",
  },
  {
    id: "cons_renato_lgpd",
    patientId: "pat_renato",
    title: "Consentimento LGPD",
    status: "signed",
    signedAt: "2026-05-13T08:20:00-03:00",
  },
];

export const patientTimeline: PatientTimelineItem[] = [
  {
    id: "time_ana_msg",
    patientId: "pat_ana",
    date: "2026-05-16T09:12:00-03:00",
    title: "Confirmação enviada",
    detail: "Template aprovado enviado pelo WhatsApp; resposta registrada.",
    kind: "mensagem",
  },
  {
    id: "time_ana_note",
    patientId: "pat_ana",
    date: "2026-05-12T18:40:00-03:00",
    title: "Nota clínica",
    detail: "Anotação de contexto mantida apenas no dashboard.",
    kind: "evolucao",
  },
  {
    id: "time_carlos_reschedule",
    patientId: "pat_carlos",
    date: "2026-05-16T11:20:00-03:00",
    title: "Reagendamento concluído",
    detail: "Agenda atualizada automaticamente após aceite de novo horário.",
    kind: "sessao",
  },
  {
    id: "time_renato_financeiro",
    patientId: "pat_renato",
    date: "2026-05-13T09:58:00-03:00",
    title: "Pagamento e recibo",
    detail: "Pix confirmado, recibo enviado e NFS-e emitida.",
    kind: "financeiro",
  },
];
